Deploy AWS infra

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -170,21 +170,68 @@ jobs:
             }
           event: fail
 
+  deploy-infrastructure:
+    docker:
+      # Docker image here that supports AWS CLI
+      - image: amazon/aws-cli
+    steps:
+      # Checkout code from git 
+      - checkout
+      - run:
+          name: Ensure back-end infrastructure exists
+          command: |
+            aws cloudformation deploy \
+              --template-file .circleci/files/backend.yml \
+              --tags project=Udapeople \
+               --stack-name "Udapeople-backend-${CIRCLE_WORKFLOW_ID}" \
+               --parameter-overrides ID="${CIRCLE_WORKFLOW_ID}"  
+            ec2-url = $(aws ec2 describe-instances --query 'Reservations[*].Instances[*].PublicIpAddress' \
+              --filters "Name=tag:Name, Values=Udapeople-backend-${CIRCLE_WORKFLOW_ID}" --output text )
+            echo "ec2-url = $ec2-url"
+            echo "Workflow ID = ${CIRCLE_WORKFLOW_ID}"
+            curl -H Content-Type: text/plain" -H "token: cb217923-dfdf-4461-ad7e-1211c8a6f80f" \
+              --request PUT --data "$ec2-url" https://api.memstash.io/values/
+              exit 1
+      - run:
+          name: Ensure front-end infrastructure exist
+          command: |
+            aws cloudformation deploy \
+              --template-file .circleci/files/frontend.yml \
+              --tags project=Udapeople \
+              --stack-name "Udapeople-frontend-khviah93rhnf"
+              --parameter-overrides ID="khviah93rhnf"
+              exit 1
+      - run:
+          name: Add back-end ip to ansible inventory
+          command: |
+            # Your code here 
+            aws ec2 describe-instances \
+              --query 'Reservations[*].Instances[*].PublicIpAddress' \
+              --filters "Name=tag:Name, Values=Udapeople-backend-${CIRCLE_WORKFLOW_ID}" --output text )
+              --output text >> .circleci/ansible/inventory.txt
+            exit 1
+      - persist_to_workspace:
+          root: ~/
+          paths:
+            - project/.circleci/ansible/inventory.txt
+      # Here's where you will add some code to rollback on failure      
+
 workflows:
   default:
     jobs:
-      - build-frontend:
-          context: slack-secrets
-      - build-backend 
-      - test-frontend:
-          requires: 
-            - build-frontend
-      - test-backend:
-          requires: 
-            - build-backend
-      - scan-frontend:
-          requires: 
-            - test-frontend
-      - scan-backend:
-          requires: 
-            - test-backend
+      # - build-frontend:
+      #     context: slack-secrets
+      # - build-backend 
+      # - test-frontend:
+      #     requires: 
+      #       - build-frontend
+      # - test-backend:
+      #     requires: 
+      #       - build-backend
+      # - scan-frontend:
+      #     requires: 
+      #       - test-frontend
+      # - scan-backend:
+      #     requires: 
+      #       - test-backend 
+      - deploy-infrastructure
